CREATE TABLE `enterprise` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `name` varchar(128) NOT NULL DEFAULT '-' COMMENT '公司名',
  `representative` varchar(40) NOT NULL DEFAULT '-' COMMENT '法人代表',
  `address` varchar(200) NOT NULL DEFAULT '-' COMMENT '公司地址',
  `region` varchar(15) NOT NULL DEFAULT '-' COMMENT '所属地区(省)',
  `city` varchar(15) NOT NULL DEFAULT '-' COMMENT '城市',
  `district` varchar(15) NOT NULL DEFAULT '-' COMMENT '区/县',
  `lat_long` varchar(80) NOT NULL DEFAULT '-' COMMENT '经纬度，json -> {"lat": "30.18484477830133", "long": "120.06383340659741"}',
  `biz_status` varchar(20) NOT NULL DEFAULT '-' COMMENT '经营状态',
  `credit_code` varchar(32) NOT NULL DEFAULT '-' COMMENT '统一社会信用代码',
  `register_code` varchar(32) NOT NULL DEFAULT '-' COMMENT '注册号',
  `phone` varchar(20) NOT NULL DEFAULT '-' COMMENT '电话',
  `email` varchar(50) NOT NULL DEFAULT '-' COMMENT '邮箱',
  `setup_time` varchar(20) NOT NULL DEFAULT '-' COMMENT '成立时间',
  `industry` varchar(50) NOT NULL DEFAULT '-' COMMENT '所属行业',
  `biz_scope` varchar(1200) NOT NULL DEFAULT '-' COMMENT '经营范围',
  `company_type` varchar(32) NOT NULL DEFAULT '-' COMMENT '公司类型',
  `registered_capital` varchar(32) NOT NULL DEFAULT '-' COMMENT '注册资本',
  `actual_capital` varchar(32) NOT NULL DEFAULT '-' COMMENT '实缴资本',
  `taxpayer_code` varchar(32) NOT NULL DEFAULT '-' COMMENT '纳税人识别号',
  `organization_code` varchar(32) NOT NULL DEFAULT '-' COMMENT '组织机构代码',
  `english_name` varchar(128) NOT NULL DEFAULT '-' COMMENT '公司英文名',
  `authorization` varchar(50) NOT NULL DEFAULT '-' COMMENT '登记机关',
  `homepage` varchar(30) NOT NULL DEFAULT '-' COMMENT '公司官网',
  `used_name` varchar(128) NOT NULL DEFAULT '-' COMMENT '公司曾用名',
  `score` varchar(32) NOT NULL DEFAULT '-' COMMENT '评分',
  `other` varchar(522) NOT NULL DEFAULT '-' COMMENT '其他',
  `gmt_create` timestamp NOT NULL DEFAULT current_timestamp() COMMENT '插入时间',
  `gmt_modify` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '最后操作时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=63 DEFAULT CHARSET=utf8mb4 COMMENT='企业信息表'
